<HomeScreen>:
    MDBoxLayout:
        size_hint: (1,1)
        orientation: "vertical"
        spacing: "20sp"


        MDTopAppBar:
            title: "WeatherApp"
            mg_bg_color: "602b7a"

        MDBoxLayout:
            MDTextField:
                hint_text: "Fill mode"
                mode: "fill"

            MDIconButton:
                icon: "android"
                mg_bg_color: "602b7a"
        
        MDLabel:
            text: "Content"
            halign: "center"